'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { MonthlyQueue } from '@/components/learning/MonthlyQueue';
import { PROGRAMS, type LearningTemplate } from '@/lib/learning';
type Settings={revision:number;contact_label:string;contact_url:string;admin_emails:string[];email_enabled:boolean};
type Data={templates:LearningTemplate[];defaults:{program:string;template_id:string}[];settings:Settings;tutors:{tutor_id:string;name:string}[];profiles:{tutor_id:string;introduction:string}[];classes:{class_id:string;name:string}[];emails:{outbox_id:string;month:string;kind:string;recipient:string;status:string;error_code:string|null;attempts:number}[];emailConfigured:boolean};
export default function LearningAdmin(){
 const [data,setData]=useState<Data|null>(null),[settings,setSettings]=useState<Settings|null>(null);
 const [draft,setDraft]=useState<Omit<LearningTemplate,'template_id'|'version'>|null>(null);
 const [tutor,setTutor]=useState(''),[intro,setIntro]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch('/api/admin/learning',{cache:'no-store'});const p=await r.json();if(!r.ok)throw Error(p.error);setData(p);setSettings({revision:p.settings.revision,contact_label:p.settings.contact_label,contact_url:p.settings.contact_url,admin_emails:p.settings.admin_emails,email_enabled:p.settings.email_enabled});}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 async function save(body:object){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/admin/learning',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const p=await r.json();if(!r.ok)throw Error(p.error);if((body as {action:string}).action==='template')setDraft(null);await load();setNotice('Đã lưu cập nhật.');}catch(e){setError(e instanceof Error?e.message:'Chưa lưu được.');}finally{setBusy(false);}}
 function stage(index:number,patch:Partial<LearningTemplate['stages'][number]>){setDraft(v=>v?{...v,stages:v.stages.map((s,i)=>i===index?{...s,...patch}:s)}:v);}
 return <div className="space-y-7"><h1 className="text-3xl font-black">Chương trình & kết nối phụ huynh</h1>{error && <p role="alert" className="rounded-lg border p-4 text-sm text-destructive">{error}</p>}{notice && <p role="status">{notice}</p>}{!data || !settings?<Button onClick={()=>load().catch(e=>setError(e.message))}>Tải cấu hình</Button>:<>
 <section className="space-y-4 rounded-2xl border bg-card p-5"><h2 className="text-xl font-bold">Lộ trình từng lớp</h2><div className="flex flex-wrap gap-2">{data.classes.map(c=><Link key={c.class_id} className="csat-btn text-xs" href={'/admin/learning/'+c.class_id}>{c.name}</Link>)}</div></section>
 <section className="space-y-4 rounded-2xl border bg-card p-5"><h2 className="text-xl font-bold">Phiên bản chương trình</h2><p className="text-sm leading-7 text-muted-foreground">Mặc định áp dụng cho lớp mới. Lớp đã chọn giáo án giữ phiên bản cũ đến khi được xác nhận thay đổi. VOI chỉ bổ sung khi đã có giáo án của trung tâm.</p>
 {data.templates.map(t=><div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-4" key={t.template_id}><div><strong>{t.title} · v{t.version}</strong><p className="mt-2 text-xs">{data.defaults.some(d=>d.template_id===t.template_id)?'Mặc định cho lớp mới':'Phiên bản được lưu giữ'}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={busy} onClick={()=>setDraft({program:t.program,title:t.title,source:t.source,stages:structuredClone(t.stages)})}>Soạn phiên bản kế tiếp</Button><Button disabled={busy || data.defaults.some(d=>d.template_id===t.template_id)} onClick={()=>save({action:'default',template_id:t.template_id})}>Đặt mặc định</Button></div></div>)}
 <Button variant="outline" disabled={busy} onClick={()=>setDraft({program:'voi',title:'CSAT · Ôn thi VOI',source:'',stages:[{title:'',range:'',description:'',outcomes:[],lessons:[]}]})}>Soạn chương trình từ giáo án mới</Button>
 {draft && <fieldset disabled={busy} className="space-y-4 rounded-xl border border-primary/30 p-4"><legend className="px-2 font-bold">Soạn phiên bản mới</legend><label className="block text-sm">Chương trình<select className="mt-2 block min-h-11 w-full rounded-lg border bg-background px-3" value={draft.program} onChange={e=>setDraft({...draft,program:e.target.value as LearningTemplate['program']})}>{Object.entries(PROGRAMS).map(([id,l])=><option value={id} key={id}>{l}</option>)}</select></label><label className="block space-y-2 text-sm">Tên giáo án<Input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label className="block space-y-2 text-sm">Nguồn và phạm vi đã xác nhận<Textarea value={draft.source} onChange={e=>setDraft({...draft,source:e.target.value})}/></label>
 {draft.stages.map((s,i)=><details key={i} className="rounded-lg border p-4"><summary className="cursor-pointer font-bold">Chặng {i+1} · {s.title || 'Chưa đặt tên'}</summary><div className="mt-4 space-y-3"><label className="block space-y-2 text-sm">Tên chặng<Input value={s.title} onChange={e=>stage(i,{title:e.target.value})}/></label><label className="block space-y-2 text-sm">Khoảng buổi<Input value={s.range} onChange={e=>stage(i,{range:e.target.value})}/></label><label className="block space-y-2 text-sm">Ý nghĩa và nội dung<Textarea value={s.description} onChange={e=>stage(i,{description:e.target.value})}/></label><label className="block space-y-2 text-sm">Mục tiêu quan sát · mỗi dòng một mục<Textarea value={s.outcomes.join('\n')} onChange={e=>stage(i,{outcomes:e.target.value.split('\n')})}/></label>
 {s.lessons.map((l,j)=><div key={j} className="space-y-3 rounded-lg border p-3">{(['range','title','description','source'] as const).map((key)=><label key={key} className="block space-y-1 text-xs">{{range:'Buổi',title:'Tên nội dung',description:'Diễn giải',source:'Nguồn'}[key]}<Textarea value={l[key]} onChange={e=>stage(i,{lessons:s.lessons.map((x,k)=>k===j?{...x,[key]:e.target.value}:x)})}/></label>)}</div>)}
 <Button variant="outline" onClick={()=>stage(i,{lessons:[...s.lessons,{range:'',title:'',description:'',source:''}]})}>Thêm nhóm buổi</Button></div></details>)}
 <div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>setDraft({...draft,stages:[...draft.stages,{title:'',range:'',description:'',outcomes:[],lessons:[]}]})}>Thêm chặng</Button><Button onClick={()=>save({action:'template',template:draft})}>Lưu thành phiên bản mới</Button><Button variant="ghost" onClick={()=>setDraft(null)}>Đóng trình soạn</Button></div></fieldset>}
 </section>
 <section className="space-y-4 rounded-2xl border bg-card p-5"><h2 className="text-xl font-bold">Kênh liên hệ và nhắc nhận xét tháng</h2><fieldset disabled={busy} className="space-y-4"><label className="block space-y-2 text-sm">Tên kênh liên hệ<Input value={settings.contact_label} onChange={e=>setSettings({...settings,contact_label:e.target.value})}/></label><label className="block space-y-2 text-sm">Đường dẫn HTTPS đã xác minh<Input value={settings.contact_url} onChange={e=>setSettings({...settings,contact_url:e.target.value})}/></label><label className="block space-y-2 text-sm">Email admin nhận tổng hợp · mỗi dòng một địa chỉ<Textarea value={settings.admin_emails.join('\n')} onChange={e=>setSettings({...settings,admin_emails:e.target.value.split('\n')})}/></label><label className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" checked={settings.email_enabled} onChange={e=>setSettings({...settings,email_enabled:e.target.checked})}/>Kích hoạt email ngày 28, dự kiến 08:00 giờ Việt Nam</label><p className="text-xs text-muted-foreground">{data.emailConfigured?'Đã có các biến cấu hình gửi email. Cần xác minh tên miền gửi trước khi bật.':'Chưa đủ cấu hình gửi email trên máy chủ. Xem tài liệu triển khai.'}</p><Button onClick={()=>save({action:'settings',...settings,admin_emails:settings.admin_emails.map(x=>x.trim()).filter(Boolean)})}>Lưu cấu hình</Button></fieldset></section>
 <section className="space-y-4 rounded-2xl border bg-card p-5"><h2 className="text-xl font-bold">Giới thiệu gia sư cho phụ huynh</h2><label className="block space-y-2 text-sm">Gia sư<select className="block min-h-11 w-full rounded-lg border bg-background px-3" value={tutor} onChange={e=>{setTutor(e.target.value);setIntro(data.profiles.find(p=>p.tutor_id===e.target.value)?.introduction||'');}}><option value="">Chọn gia sư</option>{data.tutors.map(t=><option key={t.tutor_id} value={t.tutor_id}>{t.name}</option>)}</select></label><label className="block space-y-2 text-sm">Giới thiệu đã xác minh<Textarea value={intro} maxLength={2000} onChange={e=>setIntro(e.target.value)}/></label><Button disabled={busy || !tutor} onClick={()=>save({action:'profile',tutor_id:tutor,introduction:intro})}>Công bố giới thiệu</Button></section>
 <section id="monthly" className="scroll-mt-24 rounded-2xl border bg-card p-5"><MonthlyQueue admin/></section>
 <section className="space-y-3 rounded-2xl border bg-card p-5"><h2 className="text-xl font-bold">Nhật ký email gần đây</h2><p className="text-xs text-muted-foreground">“accepted” là nhà cung cấp đã tiếp nhận, chưa xác nhận email tới hộp thư. Thao tác thử lại chỉ xử lý các thư chưa được tiếp nhận.</p><Button variant="outline" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const r=await fetch('/api/admin/learning/emails',{method:'POST'});const p=await r.json();if(!r.ok)throw Error(p.error);await load();setNotice('Đã xử lý hàng đợi email.');}catch(e){setError(e instanceof Error?e.message:'Không xử lý được.');}finally{setBusy(false);}}}>Thử lại thư đang chờ</Button>{data.emails.map(e=><div key={e.outbox_id} className="flex flex-wrap justify-between gap-2 border-b py-3 text-xs"><span>{e.month} · {e.kind} · {e.recipient}</span><span>{e.status} · {e.attempts} lần{e.error_code && ' · '+e.error_code}</span></div>)}{!data.emails.length && <p className="text-sm">Chưa phát sinh lượt gửi email.</p>}</section>
 </>}</div>;
}
