'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {useConfirm} from '@/components/ui/use-dialog';
import type {ParentImportRow} from '@/lib/parent-import';
export default function ImportParents(){
 const [preview,setPreview]=useState<{rows:ParentImportRow[];token:string}|null>(null),[selected,setSelected]=useState<string[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const {confirm,ConfirmDialog}=useConfirm();
 async function load(){const r=await fetch('/api/admin/parents/import',{cache:'no-store'});const p=await r.json();if(!r.ok)throw Error(p.error);setPreview(p);setSelected([]);}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 async function apply(){if(!await confirm({title:'Nhập hồ sơ đã chọn',description:'Tạo hồ sơ hoặc bổ sung liên kết cho '+selected.length+' học sinh. Nội dung gốc trong bảng học sinh, các liên kết khác và hồ sơ bị khóa được giữ nguyên.',confirmText:'Nhập hồ sơ',cancelText:'Xem lại'}))return;setBusy(true);setError('');try{const r=await fetch('/api/admin/parents/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:preview?.token,student_ids:selected})});const p=await r.json();if(!r.ok)throw Error(p.error);setNotice('Đã tạo '+p.created+' hồ sơ và bổ sung '+p.linked+' liên kết.');await load();}catch(e){setError(e instanceof Error?e.message:'Chưa nhập được.');}finally{setBusy(false);}}
 return <div className="space-y-5"><ConfirmDialog/><Link className="text-sm text-primary underline" href="/admin/parents">Về hồ sơ phụ huynh</Link><h1 className="text-3xl font-black">Nhập hồ sơ từ danh sách học sinh</h1><p className="text-sm leading-7 text-muted-foreground">Dùng tên và số điện thoại phụ huynh đã có. Dòng có nhiều số, tên khác nhau hoặc hồ sơ bị khóa cần kiểm tra riêng. Không tạo mật khẩu.</p>{error && <p role="alert" className="text-destructive">{error}</p>}{notice && <p role="status">{notice}</p>}<div className="flex flex-wrap gap-3"><Button variant="outline" disabled={busy} onClick={()=>load().catch(e=>setError(e.message))}>Tải lại bản xem trước</Button><Button variant="outline" disabled={busy||!preview} onClick={()=>setSelected(preview?.rows.filter(r=>r.status!=='review').slice(0,1000).map(r=>r.student_id)||[])}>Chọn các dòng hợp lệ</Button><Button disabled={busy||!selected.length} onClick={apply}>Nhập {selected.length} học sinh đã chọn</Button></div>
 <div className="space-y-3">{preview?.rows.map(r=><label key={r.student_id} className="flex items-start gap-3 rounded-xl border bg-card p-4"><input className="mt-1 size-4" type="checkbox" disabled={busy||r.status==='review'} checked={selected.includes(r.student_id)} onChange={e=>setSelected(v=>e.target.checked?[...v,r.student_id]:v.filter(id=>id!==r.student_id))}/><span className="min-w-0 text-sm"><strong>{r.name}</strong><span className="mt-2 block">{r.parent_name || 'Chưa có tên'} · {r.parent_number || 'Chưa có số'}</span><span className="mt-2 block text-xs text-muted-foreground">{r.phone && 'Chuẩn hóa: '+r.phone+' · '}{r.reason}</span></span></label>)}</div></div>;
}
