import Link from 'next/link';
import { ReviewContent } from '@/components/reviews/ReviewContent';
import { Roadmap } from '@/components/learning/Roadmap';
import type { ParentLearningData } from '@/lib/parent-learning';
import { getReviewTag } from '@/lib/student-reviews';
import { CsatNavbar } from '@/components/layout/CsatNavbar';
import { CsatBackground } from '@/components/CsatBackground';
import { ParentLogoutButton } from '@/app/parents/logout-button';
import { PrintPortal, ParentContact } from '@/app/parents/portal-actions';

const money = (value:number|null) => value === null ? 'Chưa đủ dữ liệu' : new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0}).format(value);
const card='scroll-mt-24 rounded-2xl border border-foreground/20 bg-card p-5 sm:p-7';
export function ParentPortalView({portal}:{portal:ParentLearningData}){
 if(!portal.student)return null;
 const {student,students}=portal;
 const query=(page:number)=>'/parents?'+new URLSearchParams({student:student.student_id,month:portal.month,page:String(page)}).toString()+'#reviews';
 const totals=portal.invoices.reduce((s,p)=>({amount:s.amount+Number(p.amount),received:s.received+Number(p.amount)-Number(p.balance),owed:s.owed+Math.max(0,Number(p.balance)),credit:s.credit+Math.max(0,-Number(p.balance))}),{amount:0,received:0,owed:0,credit:0});
 return <div className="relative min-h-screen bg-background"><div className="print:hidden"><CsatBackground/><CsatNavbar variant="guest"/></div>
  <style>{'@media print{@page{size:A4;margin:14mm}body{background:white!important;color:#111!important}.parent-report{padding:0!important;max-width:none!important}.parent-report section{box-shadow:none!important;border-color:#ccc!important}.parent-report h2,.parent-report h3{break-after:avoid}.parent-report tr,.parent-report #tuition .grid,.parent-report #contact article,.parent-report #attendance article{break-inside:avoid}.parent-report>header{background:white!important;color:#111!important;box-shadow:none!important;break-inside:avoid}.parent-report details>div{display:block!important}}'}</style>
  <main className="parent-report relative mx-auto max-w-6xl space-y-7 px-4 pb-12 pt-28">
   <header className="rounded-2xl border border-foreground bg-primary p-6 text-primary-foreground shadow-neo sm:p-8"><p className="text-sm">CSAT · Đồng hành cùng gia đình</p><h1 className="mt-3 font-heading text-3xl font-black sm:text-4xl">Hành trình học tập của {student.name}</h1><p className="mt-4 max-w-3xl text-sm leading-7">Theo dõi nội dung con đang học, những điều được gia sư ghi nhận và bước rèn luyện tiếp theo.</p></header>
   <div className="flex flex-wrap items-center justify-between gap-3 print:hidden"><nav aria-label="Chọn học sinh" className="flex flex-wrap gap-2">{students.map(s=><Link className={'csat-btn text-sm '+(s.student_id===student.student_id?'csat-btn--primary':'')} aria-current={s.student_id===student.student_id?'page':undefined} key={s.student_id} href={'/parents?student='+s.student_id}>{s.name}</Link>)}</nav><div className="flex flex-wrap gap-3"><PrintPortal/><ParentLogoutButton/></div></div>
   <nav aria-label="Nội dung phụ huynh" className="flex flex-wrap gap-2 print:hidden">{[['roadmap','Lộ trình'],['reviews','Nhận xét tháng'],['attendance','Buổi học'],['tuition','Học phí'],['contact','Gia sư & liên hệ']].map(([id,label])=><a className="rounded-lg border bg-card px-4 py-3 text-sm hover:border-primary" href={'#'+id} key={id}>{label}</a>)}</nav>
   <section id="roadmap" className={card}><h2 className="mb-5 text-2xl font-extrabold">Lộ trình và trọng tâm học tập</h2>
    {portal.plans.filter(p=>p.kind==='class').map(p=><article key={p.class_id} className="mb-7 space-y-4 last:mb-0"><h3 className="text-xl font-bold text-primary">{p.class_name}</h3><Roadmap body={p.body} template={p.template}/></article>)}
    {!portal.plans.some(p=>p.kind==='class') && <p className="text-sm leading-7 text-muted-foreground">Gia sư chưa công bố lộ trình lớp. Thông tin sẽ được bổ sung sau khi xác nhận chương trình và mục tiêu học.</p>}
    {portal.plans.filter(p=>p.kind==='student').map(p=><article key={p.class_id} className="mt-6 space-y-3 rounded-xl bg-accent p-5"><h3 className="font-bold">Trọng tâm riêng · {p.class_name}</h3><p className="whitespace-pre-wrap text-sm leading-7">{p.body.goal}</p><div className="flex flex-wrap gap-2">{p.body.focus_tags.map(id=><span className="rounded-lg border bg-card p-2 text-xs" key={id}>{getReviewTag(id)?.label || id}</span>)}</div>{p.body.next_step && <p className="whitespace-pre-wrap text-sm leading-7"><strong>Bước tiếp theo: </strong>{p.body.next_step}</p>}</article>)}
   </section>
   <section id="reviews" className={card}><h2 className="text-2xl font-extrabold">Nhìn lại việc học mỗi tháng</h2><p className="my-4 text-sm leading-7 text-muted-foreground">Nhận xét dựa trên quan sát và bài làm. Điểm danh hoặc số buổi học không tự thể hiện mức độ thành thạo.</p>
    <div className="space-y-4">{portal.reviews.map(r=><article key={r.review_id} className="rounded-xl border p-5"><div className="mb-4 flex flex-wrap justify-between gap-3"><strong>{r.classes?.name} · {r.month_year}</strong><span className="text-xs text-muted-foreground">Gia sư: {r.tutors?.name || 'Chưa cập nhật'}</span></div><ReviewContent review={r}/></article>)}</div>
    {!portal.reviews.length && <p className="rounded-lg border border-dashed p-5 text-sm">Chưa có nhận xét được công bố trong trang này.</p>}
    <div className="mt-5 flex flex-wrap gap-3 print:hidden">{portal.reviewPage>0 && <Link className="csat-btn text-xs" href={query(portal.reviewPage-1)}>Mới hơn</Link>}{(portal.reviewPage+1)*12<portal.reviewCount && <Link className="csat-btn text-xs" href={query(portal.reviewPage+1)}>Nhận xét trước đó</Link>}</div>
   </section>
   <section id="attendance" className={card}><div className="mb-5 flex flex-wrap items-end justify-between gap-4"><h2 className="text-2xl font-extrabold">Buổi học · {portal.month}</h2><form className="flex flex-wrap items-end gap-2 print:hidden" action="/parents"><input type="hidden" name="student" value={student.student_id}/><label className="text-xs">Tháng xem<input type="month" name="month" defaultValue={portal.month} required className="mt-2 block min-h-11 rounded-lg border bg-background px-3"/></label><button className="csat-btn text-sm" type="submit">Xem buổi học</button></form></div>
    <div className="space-y-3">{portal.attendance.map(s=><article className="rounded-xl border p-4" key={s.session_id}><div className="flex flex-wrap justify-between gap-3"><strong className="text-sm">{s.date.split('-').reverse().join('/')} · {s.start_time.slice(0,5)}–{s.end_time.slice(0,5)}</strong><span className="rounded-full bg-secondary px-3 py-1 text-xs">{s.session_status==='cancelled'?'Buổi đã hủy':s.status==='attended'?'Có mặt':s.status==='absent'?'Vắng':'Chưa có điểm danh'}</span></div><p className="mt-2 text-xs text-muted-foreground">{s.class_name}</p>{s.lesson?<div className="mt-4 space-y-2"><h3 className="font-semibold">{s.lesson.title}</h3><p className="whitespace-pre-wrap text-sm leading-7">{s.lesson.content}</p>{s.lesson.continuation && <p className="whitespace-pre-wrap text-sm leading-7"><strong>Học tiếp: </strong>{s.lesson.continuation}</p>}</div>:<p className="mt-3 text-xs text-muted-foreground">Nội dung buổi chưa được công bố.</p>}</article>)}</div>
    {!portal.attendance.length && <p className="text-sm text-muted-foreground">Chưa có buổi học được ghi nhận cho học sinh trong tháng này.</p>}
   </section>
   <section id="tuition" className={card}><h2 className="text-2xl font-extrabold">Học phí</h2><p className="my-4 text-sm leading-7 text-muted-foreground">Admin đối chiếu và chốt sổ thủ công. Khoản tạm tính tiếp tục được giữ nguyên trạng thái khi sang tháng mới, cho đến khi trung tâm chốt sổ.</p>
    <div className="mb-6 grid grid-cols-2 gap-3 lg:grid-cols-4">{[['Đã chốt',totals.amount],['Đã ghi nhận thanh toán (ròng)',totals.received],['Còn phải đóng',totals.owed],['Dư / cần hoàn',totals.credit]].map(([label,value])=><div key={label} className="rounded-xl border bg-accent/40 p-4"><p className="text-xs">{label}</p><strong className="mt-2 block text-lg">{money(Number(value))}</strong></div>)}</div>
    <h3 className="mb-3 font-bold">Các kỳ đã chốt</h3><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-3">Kỳ / lớp</th><th className="p-3">Học phí đã chốt</th><th className="p-3">Đã thanh toán (ròng)</th><th className="p-3">Số dư</th></tr></thead><tbody>{portal.invoices.map(p=><tr className="border-b" key={p.payment_id}><td className="p-3">{p.period}<span className="block text-xs text-muted-foreground">{p.class_name || 'Chưa có liên kết lớp'}</span></td><td className="p-3">{money(p.amount)}</td><td className="p-3">{money(Number(p.amount)-Number(p.balance))}</td><td className="p-3">{Number(p.balance)<0?'Dư / cần hoàn: ':Number(p.balance)>0?'Còn đóng: ':'Đã đủ: '}{money(Math.abs(Number(p.balance)))}</td></tr>)}</tbody></table></div>
    {!portal.invoices.length && <p className="my-4 text-sm text-muted-foreground">Chưa có kỳ học phí đã chốt.</p>}
    <h3 className="mb-3 mt-6 font-bold">Tạm tính · Chưa chốt</h3><div className="space-y-3">{portal.provisional.map((p,i)=><div key={i} className="flex flex-wrap justify-between gap-3 rounded-xl border border-dashed p-4"><div><strong className="text-sm">{p.class_name} · {p.month}</strong><p className="mt-2 text-xs text-muted-foreground">{p.unknown>0?p.unknown+' buổi còn thiếu điểm danh hoặc học phí; số tiền dưới đây chưa đầy đủ.':'Theo buổi học và mức phí đã ghi nhận; chờ đối chiếu.'}</p></div><span className="font-bold">{money(p.amount)}</span></div>)}</div>{!portal.provisional.length && <p className="text-sm text-muted-foreground">Chưa có khoản tạm tính từ các buổi đã diễn ra.</p>}
   </section>
   <section id="contact" className={card}><h2 className="mb-5 text-2xl font-extrabold">Gia sư và kết nối với CSAT</h2><div className="mb-6 grid gap-4 sm:grid-cols-2">{portal.tutors.map((t,i)=><article key={i} className="rounded-xl border p-4"><h3 className="font-bold">{t.name || 'Chưa phân gia sư'}</h3><p className="my-2 text-xs text-primary">{t.class_name}</p>{t.introduction && <p className="whitespace-pre-wrap text-sm leading-7">{t.introduction}</p>}</article>)}</div><div className="print:hidden"><ParentContact name={student.name} label={portal.contact?.label||''} url={portal.contact?.url||''}/></div></section>
   <p className="text-xs leading-6 text-muted-foreground">Kết quả contest CSATOJ sẽ được bổ sung sau khi hoàn tất kết nối và đối chiếu tài khoản học sinh.</p>
  </main></div>;
}