'use client';
import { useState } from 'react';
import Link from 'next/link';
import type { ParentCurriculumProgress } from '@/lib/parent-curriculum-progress';
import type { LearningBody, LearningTemplate } from '@/lib/learning';
import { PROGRAMS } from '@/lib/learning';
import { effectiveStages, isStructuredCurriculum } from '@/lib/curriculum';
import { getReviewTag } from '@/lib/student-reviews';
export function Roadmap({body,template,progress,articleLinks={}}:{body:LearningBody;template?:LearningTemplate|null;progress?:ParentCurriculumProgress;articleLinks?:Record<string,string>}){
 const stages=effectiveStages(template,body);
 const current=progress?stages.find(s=>s.originalIndex===progress.stage?.originalIndex):stages.find(s=>isStructuredCurriculum(template)?s.id===body.curriculum?.current_stage_id:s.originalIndex===body.stage_index);
 const [selected,setSelected]=useState<string|null>(null);
 const stage=stages.find(s=>(s.id??String(s.originalIndex))===selected)??current??stages[0];
 return <div className="space-y-5">
  <div className="flex flex-wrap gap-2 text-xs font-semibold"><span className="rounded-full border px-3 py-2">{body.program?PROGRAMS[body.program]:'Chưa xác nhận chương trình'}</span>{body.format&&<span className="rounded-full border px-3 py-2">{body.format==='individual'?'Học 1–1':'Học nhóm'}</span>}{body.program==='basic'&&isStructuredCurriculum(template)&&<span className="rounded-full border px-3 py-2">Tầng {(body.curriculum?.parts??['A','B']).join(' + ')}</span>}</div>
  {template?<>
   <p className="text-xs leading-6 text-muted-foreground">{progress?.source==='sessions'?(progress.preparing?'Lớp đang chuẩn bị cho chặng đầu tiên.':'Chặng định hướng theo '+progress.completedSessions+' buổi lớp đã hoàn thành.')+' Số buổi không thể hiện mức độ thành thạo của con.':'Khung nội dung định hướng việc học, không thể hiện học sinh đã thành thạo. '+(current?'Gia sư đang ghi nhận trọng tâm: '+current.title+'.':'Chặng đang tập trung chưa được xác nhận.')}</p>
   <div className="roadmap-stage-nav grid grid-cols-2 gap-2 sm:grid-cols-3" aria-label="Chọn chặng để xem nội dung">{stages.map((s,i)=><button type="button" key={s.id??s.originalIndex} aria-pressed={stage===s} onClick={()=>setSelected(s.id??String(s.originalIndex))} className={'roadmap-stage min-h-24 rounded-xl border p-3 text-left '+(stage===s?'bg-primary text-primary-foreground':'bg-card')}><span className="mb-2 block font-mono text-xs">CHẶNG {String(i+1).padStart(2,'0')}{s===current?(progress?.preparing?' · CHUẨN BỊ':' · ĐANG TẬP TRUNG'):''}</span><span className="text-sm font-bold">{s.title}</span></button>)}</div>
   <div className="roadmap-detail grid gap-5 lg:grid-cols-[1fr_260px]">
    <div className="min-w-0 rounded-xl border p-5">{stage?<><p className="mb-2 text-xs text-muted-foreground">Đang xem nội dung · không phải trạng thái hoàn thành</p><h3 className="text-xl font-extrabold">{stage.title}</h3><p className="my-3 text-sm leading-7">{stage.description}</p><div className="space-y-2">{stage.lessons.map((l,i)=><details key={l.code??i} className="rounded-lg border bg-card px-3"><summary className="min-h-11 cursor-pointer py-3 text-sm font-semibold">{l.code?l.code+' · ':''}{l.title}</summary><div className="pb-4 text-sm leading-7">{l.description||'Nội dung luyện tập cụ thể được gia sư cập nhật theo buổi học.'}{l.code&&articleLinks[l.code]&&<Link className="parent-read-topic" href={articleLinks[l.code]} aria-label={'Đọc chuyên đề: '+l.title}>Đọc chuyên đề <span aria-hidden="true">↗</span></Link>}</div></details>)}</div></>:<p className="text-sm">Chưa có chủ đề trong cấu hình đang xem.</p>}</div>
    <aside className="roadmap-focus space-y-4 rounded-xl border bg-accent p-5"><h3 className="font-bold">Trọng tâm đồng hành</h3><p className="whitespace-pre-wrap text-sm leading-7">{body.goal||'Gia sư sẽ bổ sung mục tiêu sau khi trao đổi và ghi nhận quá trình học.'}</p>{body.focus_tags.length>0&&<div className="flex flex-wrap gap-2">{body.focus_tags.map(id=><span key={id} className="rounded-lg border bg-card p-2 text-xs">{getReviewTag(id)?.label||id}</span>)}</div>}{body.next_step&&<p className="whitespace-pre-wrap text-sm leading-7"><strong>Bước tiếp theo: </strong>{body.next_step}</p>}</aside>
   </div>
   <details className="roadmap-all rounded-xl border p-4"><summary className="min-h-11 cursor-pointer py-3 text-sm font-bold">Xem toàn bộ nội dung của lớp</summary><div className="space-y-5 pt-3">{stages.map(s=><section key={s.id??s.originalIndex}><h3 className="font-bold">{s.title}</h3><ul className="mt-2 space-y-2 text-sm leading-7">{s.lessons.map((l,i)=><li key={l.code??i}><strong>{l.code?l.code+' · ':''}{l.title}</strong>{l.description&&<p>{l.description}</p>}{l.code&&articleLinks[l.code]&&<Link className="parent-read-topic" href={articleLinks[l.code]} aria-label={'Đọc chuyên đề: '+l.title}>Đọc chuyên đề <span aria-hidden="true">↗</span></Link>}</li>)}</ul></section>)}</div></details>
  </>:<div className="space-y-4 rounded-xl border border-dashed p-5"><p className="text-sm leading-7">{body.program==='voi'?'Khung HSGQG chờ giáo án được trung tâm xác nhận.':body.program==='custom'?'Lộ trình luyện thi được điều chỉnh theo kỳ thi và mục tiêu của lớp.':'Gia sư chưa công bố phiên bản giáo án cho lớp.'}</p>{body.goal&&<p className="text-sm leading-7">{body.goal}</p>}<div className="flex flex-wrap gap-2">{body.focus_tags.map(id=><span key={id} className="rounded-lg border p-2 text-xs">{getReviewTag(id)?.label||id}</span>)}</div>{body.next_step&&<p className="text-sm leading-7">{body.next_step}</p>}</div>}
 </div>;
}
