'use client';
import { useCallback, useEffect, useState } from 'react';
import { consultationStatuses, consultationRoles, mailStatuses, type ConsultationInput } from '@/lib/consultations';
import { EmailReconciliation,type Reconciliation } from '@/components/learning/EmailReconciliation';
import { goals, levels } from '@/lib/learning-guidance';
type Mail={status:keyof typeof mailStatuses;attempts:number;error_code:string|null;next_attempt_at:string;email_reconciliations?:Reconciliation[]};
type Row={request_id:string;data:ConsultationInput;created_at:string;status:keyof typeof consultationStatuses;revision:number;consultation_email_outbox:Mail|Mail[]|null};
const field='min-h-11 rounded-lg border border-input bg-card px-3 py-2 text-sm';
export default function ConsultationsAdmin(){
 const [mailFilter,setMailFilter]=useState(''),[counts,setCounts]=useState<{newCount:number|null;contactedCount:number|null}>({newCount:null,contactedCount:null}),[missing,setMissing]=useState<string[]>([]);
 const [rows,setRows]=useState<Row[]>([]),[filter,setFilter]=useState(''),[offset,setOffset]=useState(0),[total,setTotal]=useState(0),[busy,setBusy]=useState(''),[loading,setLoading]=useState(true),[notice,setNotice]=useState(''),[error,setError]=useState(''),[mailEnabled,setMailEnabled]=useState(false);
 const load=useCallback(async(signal?:AbortSignal)=>{setLoading(true);try{const response=await fetch(`/api/admin/consultations?${new URLSearchParams({status:filter,mail:mailFilter,offset:String(offset)})}`,{cache:'no-store',signal});const data=await response.json();if(!response.ok)throw new Error(data.error);setRows(data.data);setTotal(data.total);setCounts({newCount:data.newCount,contactedCount:data.contactedCount});setMissing(data.configurationMissing||[]);setMailEnabled(data.emailEnabled);setError('');}catch(e){if(signal?.aborted)return;setError(e instanceof Error?e.message:'Không tải được yêu cầu tư vấn.');}finally{if(!signal?.aborted)setLoading(false);}},[filter,mailFilter,offset]);
 useEffect(()=>{const controller=new AbortController();void load(controller.signal);return()=>controller.abort();},[load]);
 async function act(row:Row,action:'status'|'retry',status?:string){if(busy)return;setBusy(row.request_id);setNotice('');setError('');try{const response=await fetch('/api/admin/consultations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,request_id:row.request_id,...(action==='status'?{status,revision:row.revision}:{})})});const data=await response.json();if(!response.ok)throw new Error(data.error);setNotice(action==='status'?'Đã cập nhật trạng thái tư vấn.':data.state==='accepted'?'Nhà cung cấp đã tiếp nhận email.':data.state==='failed'?'Gửi email lỗi. Xem trạng thái và thử lại sau thời gian chờ.':data.state==='disabled'||data.state==='unconfigured'?'Gửi email chưa được bật hoặc thiếu cấu hình.':'Chưa thể gửi lại. Có thể đang xử lý, trong thời gian chờ hoặc cần kiểm tra thủ công.');await load();}catch(e){setError(e instanceof Error?e.message:'Thao tác chưa hoàn tất.');}finally{setBusy('');}}
 return <><div><p className="text-xs font-bold uppercase tracking-widest text-primary">Tiếp nhận & liên hệ</p><h1 className="text-3xl font-black mt-2">Yêu cầu tư vấn</h1><p className="text-sm text-muted-foreground mt-2">Theo dõi yêu cầu từ trang giới thiệu. Trạng thái tư vấn và trạng thái gửi email được quản lý riêng.</p></div>
 <div className="flex flex-wrap items-center gap-3"><label className="text-sm font-semibold">Trạng thái <select className={field} value={filter} onChange={e=>{setFilter(e.target.value);setOffset(0);}}><option value="">Tất cả</option>{Object.entries(consultationStatuses).map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label><label className="text-sm font-semibold">Email <select className={field} value={mailFilter} onChange={e=>{setMailFilter(e.target.value);setOffset(0);}}><option value="">Tất cả</option>{Object.entries(mailStatuses).map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label><button className={field} disabled={loading} onClick={()=>void load()}>Tải lại</button><span className="text-sm">{total} yêu cầu</span></div>
 <p className="text-sm">Chưa liên hệ: {counts.newCount??"Chưa có số liệu"} · Đang theo dõi: {counts.contactedCount??"Chưa có số liệu"}</p>
 {missing.length>0&&<p role="status" className="text-sm">Thiếu cấu hình máy chủ: {missing.join(", ")}. Yêu cầu vẫn được lưu để admin xử lý.</p>}
 {!mailEnabled&&<p className="border border-input bg-card p-4 rounded-xl text-sm">Email tư vấn chưa được bật ở môi trường này. Yêu cầu đã lưu vẫn hiển thị để admin liên hệ.</p>}
 {error&&<p role="alert" className="border border-destructive rounded-xl p-4">{error}</p>}{notice&&<p role="status" className="border border-primary rounded-xl p-4">{notice}</p>}
 {loading?<p role="status">Đang tải…</p>:!rows.length&&!error?<p className="csat-card bg-card p-6">Chưa có yêu cầu trong nhóm này.</p>:<div className="space-y-4">{rows.map(row=>{const d=row.data,mail=Array.isArray(row.consultation_email_outbox)?row.consultation_email_outbox[0]:row.consultation_email_outbox;return <article key={row.request_id} className="csat-card bg-card p-5 space-y-4"><div className="flex justify-between gap-4 flex-wrap"><div><h2 className="text-lg font-extrabold">{d.name}</h2><p className="text-sm text-muted-foreground">{consultationRoles[d.role]} · {new Intl.DateTimeFormat('vi-VN',{dateStyle:'short',timeStyle:'short',timeZone:'Asia/Ho_Chi_Minh'}).format(new Date(row.created_at))} (VN)</p></div><label className="text-sm">Trạng thái tư vấn<select aria-label={`Trạng thái tư vấn của ${d.name}`} className={`${field} block`} disabled={!!busy} value={row.status} onChange={e=>void act(row,'status',e.target.value)}>{Object.entries(consultationStatuses).map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label></div><div className="grid sm:grid-cols-2 gap-3 text-sm"><p>Điện thoại: <a className="underline" href={`tel:${d.phone}`}>{d.phone}</a></p><p className="break-all">Email: {d.email||'Không cung cấp'}</p><p>Cấp học: {d.level==='undecided'?'Cần trao đổi thêm':levels[d.level]}{d.school_year?` · ${d.school_year}`:''}</p><p>Mục tiêu: {goals[d.goal]}</p></div><details><summary className="cursor-pointer min-h-11 flex items-center font-semibold text-sm">Xem nội dung và mã yêu cầu</summary><p className="whitespace-pre-wrap break-words text-sm mt-2">{d.message||'Không có lời nhắn.'}</p><p className="text-xs text-muted-foreground break-all mt-3">Mã: {row.request_id} · Đã đồng ý lưu thông tin và liên hệ tư vấn.</p></details><div className="border-t border-input pt-4 flex flex-wrap gap-3 items-center text-sm"><span>Email: {mail?mailStatuses[mail.status]:'Chưa có trạng thái'}</span>{mail&&<span className="text-muted-foreground">{mail.attempts} lần thử{mail.error_code?` · ${mail.error_code}`:''}</span>}{mailEnabled&&mail&&!mail.email_reconciliations?.some(n=>n.outcome!=='checked')&&['queued','failed','sending'].includes(mail.status)&&<button className={field} disabled={!!busy} onClick={()=>void act(row,'retry')}>{busy===row.request_id?'Đang xử lý…':'Thử gửi email'}</button>}{mail?.status==='failed'&&<p className="w-full text-muted-foreground">Có thể thử lại từ {new Date(mail.next_attempt_at).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'})} (VN), nếu còn đủ điều kiện.</p>}{mail&&['failed','manual_review'].includes(mail.status)&&<EmailReconciliation kind="consultation" id={row.request_id} notes={mail.email_reconciliations} onSaved={load}/>} {mail?.status==='manual_review'&&!mail.email_reconciliations?.some(n=>n.outcome!=='checked')&&<p className="w-full text-muted-foreground">Cần kiểm tra trên nhà cung cấp email trước khi xử lý tiếp; không tự động gửi lại.</p>}</div></article>;})}</div>}
 <div className="flex gap-3 items-center"><button className={field} disabled={offset===0||loading} onClick={()=>setOffset(v=>Math.max(0,v-50))}>Trang trước</button><span className="text-sm">Trang {Math.floor(offset/50)+1}</span><button className={field} disabled={offset+50>=total||loading} onClick={()=>setOffset(v=>v+50)}>Trang sau</button></div></>;
}
