const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');
const root=path.resolve(__dirname,'../..');
const input=()=>({request_id:'30000000-0000-4000-8000-000000000001',role:'parent',name:'Test Parent',phone:'0912345678',email:'parent@example.test',level:'thcs',goal:'specialist',program:'co-ban',school_year:'8',message:'Test only',consent:true,website:''});
function load(relative,s={}){const filename=path.join(root,relative),m=new Module(filename,module);m.paths=module.paths;const req=m.require.bind(m);m.require=name=>{
 if(name==='server-only')return {};
 if(name==='next/server')return {NextResponse:{json:(b,o)=>Response.json(b,o)}};
 if(name==='@/lib/supabase/service')return {createAdminClient:()=>({rpc:(name,args)=>{(s.calls??=[]).push({name,args});const result=Promise.resolve(s.rpc?s.rpc(name,args):{data:args.p_id,error:s.dbError});result.abortSignal=()=>result;return result;}})};
 if(name==='@/lib/business-api')return {businessSession:async()=>({response:Response.json({error:'denied'},{status:s.denied||403})}),businessError:()=>Response.json({error:'error'},{status:500})};
 if(name==='@/lib/consultation-email'&&s.mockMail)return {consultationMailPayload:()=>({to:['csattutor@gmail.com'],subject:'test',text:'test'}),sendConsultationEmail:async()=>{s.sent=true;if(s.mailError)throw Error('fake');}};
 if(name.startsWith('@/lib/'))return load(name.slice(2)+'.ts',s);
 if(name.startsWith('./')&&name.endsWith('.json'))return require(path.join(path.dirname(filename),name));
 if(name.startsWith('./')&&!name.endsWith('.json'))return load(path.relative(root,path.join(path.dirname(filename),name+'.ts')),s);
 return req(name);
 };m._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,filename);return m.exports;}
function env(){process.env.CONSULTATIONS_ENABLED='true';process.env.CONSULTATIONS_HASH_KEY='synthetic-test-only-key';process.env.APP_ORIGIN='https://portal.example.test';delete process.env.VERCEL;delete process.env.CONSULTATIONS_EMAIL_ENABLED;}
function request(body=input(),headers={}){return new Request('https://portal.example.test/api/consultations',{method:'POST',headers:{origin:'https://portal.example.test','content-type':'application/json',...headers},body:JSON.stringify(body)});}
test('mapping never treats custom or university as HSGQG; public curriculum preserves the new approved topic codes and titles',()=>{const learning=load('lib/public-learning.ts');for(const level of ['thcs','thpt']){assert.equal(learning.recommendedProgram(level,'specialist'),'co-ban');assert.equal(learning.recommendedProgram(level,'thcs'),'co-ban');assert.equal(learning.recommendedProgram(level,'province'),'nang-cao');assert.equal(learning.recommendedProgram(level,'national'),'hsgqg');}assert.equal(learning.recommendedProgram('university','national'),'consultation');assert.equal(learning.recommendedProgram('thpt','custom'),'consultation');assert.equal(learning.validGoal('__proto__'),'undecided');for(const [slug,code] of [['co-ban','basic'],['nang-cao','advanced']]){const source=require('../../lib/learning-curriculum-20260922.json').find(t=>t.program===code);const stages=learning.publicStages(slug);assert.equal(stages.length,source.stages.length);assert.deepEqual(stages.flatMap(s=>s.lessons),source.stages.flatMap(s=>s.lessons.map(({code,title})=>({range:code,title}))));assert.doesNotMatch(JSON.stringify(stages),/Đề xuất|30 buổi|35 buổi/);}});
test('public API denies foreign or missing origin, malformed/oversized input, honeypot and missing consent before DB',async()=>{env();const s={mockMail:true},route=load('app/api/consultations/route.ts',s);for(const headers of [{origin:'https://evil.test'},{origin:''}])assert.equal((await route.POST(request(input(),headers))).status,403);for(const patch of [{consent:false},{website:'bot'},{phone:'123'},{role:'admin'},{message:'a'.repeat(2001)},{program:'hsgqg'}])assert.equal((await route.POST(request({...input(),...patch}))).status,422);assert.equal((await route.POST(request({...input(),message:'a'.repeat(20000)}))).status,413);assert.equal(s.calls,undefined);});
test('saved request succeeds even on mail failure; DB/rate errors never claim success',async()=>{env();const s={mockMail:true,mailError:true},route=load('app/api/consultations/route.ts',s);const result=await route.POST(request());assert.equal(result.status,201);assert.equal((await result.json()).request_id,input().request_id);assert.equal(s.calls.length,1);assert.match(s.calls[0].args.p_source_hash,/^[a-f0-9]{64}$/);assert.ok(!('request_id' in s.calls[0].args.p_data));for(const [code,status] of [['P0429',429],['23505',409],['oops',503]]){s.dbError={code};s.sent=false;assert.equal((await route.POST(request())).status,status);assert.equal(s.sent,false);}});
test('disabled intake cannot write and admin mutations require authentication',async()=>{env();delete process.env.CONSULTATIONS_ENABLED;const s={mockMail:true};assert.equal((await load('app/api/consultations/route.ts',s).POST(request())).status,503);assert.equal(s.calls,undefined);for(const denied of [401,403]){const r=load('app/api/admin/consultations/route.ts',{denied});assert.equal((await r.POST(request())).status,denied);assert.equal((await r.GET(request())).status,denied);}});
test('mail is disabled locally and on preview even with keys; payload has fixed recipient and safe reply-to',async()=>{env();const s={},mail=load('lib/consultation-email.ts',s);process.env.CONSULTATIONS_EMAIL_ENABLED='true';process.env.RESEND_API_KEY='test-only';process.env.CSAT_EMAIL_FROM='sender@example.test';for(const mode of ['development','preview']){process.env.VERCEL_ENV=mode;assert.equal((await mail.sendConsultationEmail(input().request_id)).state,'disabled');}assert.equal(s.calls,undefined);const payload=mail.consultationMailPayload(input());assert.deepEqual(payload.to,['csattutor@gmail.com']);assert.equal(payload.reply_to,'parent@example.test');assert.match(payload.text,/Chuyên Tin/);});
test('provider timeout stays failed and accepted responses use stable idempotency key with frozen payload',async()=>{env();process.env.VERCEL_ENV='production';process.env.CONSULTATIONS_EMAIL_ENABLED='true';process.env.RESEND_API_KEY='test-only';process.env.CSAT_EMAIL_FROM='sender@example.test';const original=global.fetch;try{const s={rpc:(name)=>({data:name==='claim_consultation_email'?{lease_id:'fake-lease',payload:{from:'frozen@example.test',to:['csattutor@gmail.com'],text:'synthetic'}}:true})},mail=load('lib/consultation-email.ts',s);let options;global.fetch=async(url,o)=>{options=o;return Response.json({id:'test-provider'});};assert.equal((await mail.sendConsultationEmail(input().request_id)).state,'accepted');assert.equal(options.headers['Idempotency-Key'],'csat-consultation-'+input().request_id);assert.equal(JSON.parse(options.body).from,'frozen@example.test');global.fetch=async()=>{throw Error('fake timeout');};assert.equal((await mail.sendConsultationEmail(input().request_id)).state,'failed');assert.equal(s.calls.at(-1).args.p_error,'transport_uncertain');}finally{global.fetch=original;delete process.env.CONSULTATIONS_EMAIL_ENABLED;delete process.env.VERCEL_ENV;}});
