const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');
function load(relative,s={}){const filename=path.resolve(__dirname,'../..',relative),m=new Module(filename,module);m.paths=module.paths;const req=m.require.bind(m);m.require=n=>{
 if(n==='server-only')return {};
 if(n==='next/server')return {NextResponse:{json:(b,o)=>Response.json(b,o),next:()=>({headers:new Headers()})}};
 if(n==='@supabase/ssr')return {createServerClient:()=>{s.authCalled=true;throw Error('Unexpected session fetch');}};
 if(n==='@/lib/auth-routing')return {authRedirect:()=>null};
 const rpc=(name,args)=>{(s.calls??=[]).push({name,args});const result=Promise.resolve(s.rpc?s.rpc(name,args):{data:{updated:true}});result.abortSignal=()=>result;return result;};
 if(n==='@/lib/supabase/service')return {createAdminClient:()=>({rpc})};
 if(n==='@/lib/business-api')return {businessSession:async()=>s.denied?{response:Response.json({error:'denied'},{status:s.denied})}:{supabase:{rpc},user:{id:'test-admin'}},businessError:e=>Response.json({error:e.message},{status:409})};
 if(n==='@/lib/review-email'&&s.mockProcess)return {mailConfiguration:()=>({origin:'https://test.example',sender:'test@example.test',replyTo:'csattutor@gmail.com'}),processReviewEmails:async()=>{s.processed=true;return {accepted:0};}};
 if(n.startsWith('@/'))return load(n.slice(2)+'.ts',s);
 return req(n);
 };m._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,filename);return m.exports;}
function env(){process.env.VERCEL_ENV='production';process.env.CRON_SECRET='synthetic-secret';process.env.APP_ORIGIN='https://portal.example.test';process.env.CSAT_EMAIL_FROM='CSAT <test@example.test>';process.env.CSAT_EMAIL_REPLY_TO='csattutor@gmail.com';process.env.RESEND_API_KEY='test-only';}
function request(body,auth){return new Request('https://portal.example.test/api/admin/learning/emails',{method:body===undefined?'GET':'POST',headers:{origin:'https://portal.example.test',...(auth?{authorization:auth}:{})},...(body===undefined?{}:{body:typeof body==='string'?body:JSON.stringify(body)})});}
test('cron rejects missing/wrong bearer and never invokes sender on Preview; exact proxy bypass avoids cookie auth',async()=>{env();const s={mockProcess:true},route=load('app/api/cron/monthly-reviews/route.ts',s);for(const a of [undefined,'Bearer bad','Basic synthetic-secret'])assert.equal((await route.GET(request(undefined,a))).status,401);assert.equal(s.processed,undefined);process.env.VERCEL_ENV='preview';assert.equal((await route.GET(request(undefined,'Bearer synthetic-secret'))).status,200);assert.equal(s.processed,undefined);process.env.VERCEL_ENV='production';assert.equal((await route.GET(request(undefined,'Bearer synthetic-secret'))).status,200);assert.equal(s.processed,true);const proxy=load('proxy.ts',s);await proxy.proxy({nextUrl:{pathname:'/api/cron/monthly-reviews'}});assert.equal(s.authCalled,undefined);});
test('admin recovery validates body, keeps empty POST compatible, separates preparation from sending and denies tutor',async()=>{env();const s={mockProcess:true,rpc:()=>({data:{prepared:true}})},r=load('app/api/admin/learning/emails/route.ts',s);assert.equal((await r.POST(request('{broken'))).status,422);assert.equal((await r.POST(request({action:'prepare',month:'2026-06'}))).status,422);assert.equal((await r.POST(request({action:'preview',month:'2026-06'}))).status,200);assert.equal(s.calls.at(-1).args.p_action,'preview');await r.POST(request({action:'prepare',month:'2026-06',token:'a'.repeat(32),request_id:'30000000-0000-4000-8000-000000000001'}));assert.equal(s.processed,undefined);assert.equal(s.calls.at(-1).args.p_action,'prepare_manual');await r.POST(request(''));assert.equal(s.processed,true);for(const denied of [401,403])assert.equal((await load('app/api/admin/learning/emails/route.ts',{denied}).POST(request(''))).status,denied);});
test('batch checks persistence, uses frozen payload/key and leaves ambiguous results for same-key recovery',async()=>{env();const original=global.fetch;try{let sent=0;const job={outbox_id:'job-one',lease_id:'lease-one',payload:{from:'frozen@example.test',reply_to:'frozen-reply@example.test',text:'Synthetic'}};const s={rpc:(n,a)=>({data:a.p_action==='claim'?(sent?null:job):a.p_action==='finish'?{updated:false}:{disabled:false}})};global.fetch=async(u,o)=>{sent++;assert.equal(o.headers['Idempotency-Key'],'csat-review-job-one');assert.deepEqual(JSON.parse(o.body),job.payload);return Response.json({id:'provider-test'});};await assert.rejects(()=>load('lib/review-email.ts',s).processReviewEmails(),/ghi được/);assert.equal(sent,1);assert.equal(s.calls.at(-1).args.p_data.status,'accepted');}finally{global.fetch=original;}});
test('batch respects 35 limit and reconciles digest after last item; no actual network or sleeps',async()=>{env();const fetch=global.fetch,timer=global.setTimeout;try{global.setTimeout=(cb)=>timer(cb,0);let claimed=0,sent=0;const s={rpc:(n,a)=>({data:a.p_action==='claim'?{outbox_id:'job-'+(++claimed),lease_id:'lease',payload:{text:'test'}}:a.p_action==='finish'?{updated:true}:{disabled:false}})};global.fetch=async()=>{sent++;return Response.json({id:'test-'+sent});};const result=await load('lib/review-email.ts',s).processReviewEmails(true);assert.equal(result.accepted,35);assert.equal(sent,35);assert.equal(s.calls.at(-1).args.p_action,'admin');assert.equal(s.calls.find(c=>c.args.p_action==='prepare').args.p_data.reply_to,'csattutor@gmail.com');}finally{global.fetch=fetch;global.setTimeout=timer;}});
test('batch skips disabled config, maps 429 and timeout to failure, and does not start jobs without time budget',async()=>{env();const fetch=global.fetch,timer=global.setTimeout,now=Date.now;try{const off={rpc:()=>({data:{disabled:true}})};delete process.env.RESEND_API_KEY;assert.equal((await load('lib/review-email.ts',off).processReviewEmails()).disabled,true);env();global.setTimeout=cb=>timer(cb,0);for(const mode of ['429','timeout']){let claimed=0;const s={rpc:(n,a)=>({data:a.p_action==='claim'?(claimed++?null:{outbox_id:'j',lease_id:'l',payload:{}}):{updated:true}})};global.fetch=async()=>{if(mode==='timeout')throw Error('uncertain');return Response.json({},{status:429});};assert.equal((await load('lib/review-email.ts',s).processReviewEmails()).failed,1);assert.equal(s.calls.find(c=>c.args.p_action==='finish').args.p_data.error_code,mode==='429'?'provider_http_429':'transport_uncertain');}let time=0;Date.now=()=>{time+=30000;return time;};const s={rpc:()=>({data:{disabled:false}})};await load('lib/review-email.ts',s).processReviewEmails();assert.ok(!s.calls.some(c=>c.args.p_action==='claim'));}finally{global.fetch=fetch;global.setTimeout=timer;Date.now=now;}});
