const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module');
const ts=require('../../node_modules/typescript'),sharp=require('../../node_modules/sharp');
const tid='20000000-0000-4000-8000-000000000020';
function load(relative,s={}){const filename=path.resolve(__dirname,'../..',relative),m=new Module(filename,module);m.paths=Module._nodeModulePaths(path.dirname(filename));const original=m.require.bind(m);
const rpc=async(name,args)=>{(s.calls??=[]).push({name,args});if(name==='claim_tutor_avatar_cleanup')return {data:s.claim??true};return s.saveError?{error:{code:'40001',message:'conflict'}}:{data:{...args.p_data,tutor_id:tid,name:'Synthetic tutor',revision:args.p_revision+1,avatar_path:args.p_data.avatar_path??null,previous_avatar_path:s.previous??null}};};
const from=table=>{let op='select';const q={select(){return q;},eq(){return q;},not(){return q;},insert(row){op='insert';(s.assets??=[]).push(row);return q;},update(){op='update';return q;},delete(){op='delete';s.deleted=true;return q;},maybeSingle:async()=>({data:table==='tutors'?(s.noTutor?null:{tutor_id:tid,name:'Synthetic tutor'}):(s.profile??null)}),single:async()=>({data:{path:'ready'}}),then(resolve){resolve({data:null,error:s.registryError?{code:'42P01'}:null});}};return q;};
const supabase={from,rpc,storage:{from:()=>({upload:async(p,buffer,opts)=>{s.upload={p,buffer,opts};return {error:s.uploadError?{}:null};},remove:async paths=>{s.removed=paths;return {error:s.removeError?{}:null};}})}};
m.require=n=>{if(n==='next/server')return {NextResponse:{json:(b,o)=>Response.json(b,o)}};if(n==='./business-api')return {businessSession:async(admin,req)=>{s.adminRequired=admin;if(s.denied)return {response:Response.json({}, {status:s.denied})};return {supabase,user:{id:'synthetic'}};},businessError:e=>Response.json({error:e.message},{status:409})};if(n==='./supabase/service')return {createAdminClient:()=>supabase};if(n.startsWith('./')&&fs.existsSync(path.resolve(path.dirname(filename),n+'.ts')))return load(path.relative(path.resolve(__dirname,'../..'),path.resolve(path.dirname(filename),n+'.ts')),s);return original(n);};
m._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,filename);return m.exports;}
const data=extra=>({revision:0,introduction:'Giới thiệu',major:'',university:'',achievements:'',avatar_action:'keep',...extra});
function request(input,file){const f=new FormData();f.set('profile',JSON.stringify(input));if(file)f.set('avatar',file);return new Request('https://portal.example.test/api/tutor/profile',{method:'PUT',headers:{origin:'https://portal.example.test'},body:f});}
const image=async()=>new File([await sharp({create:{width:700,height:550,channels:3,background:'#2b50e0'}}).jpeg().toBuffer()],'avatar.jpg',{type:'image/jpeg'});
test('avatar normalizer creates square WebP without metadata and rejects corrupt, mismatched, oversized, animated and excessive pixels',async()=>{const {normalizeTutorAvatar:normalize}=load('lib/tutor-avatar.ts');const result=await normalize(await image()),meta=await sharp(result).metadata();assert.equal(meta.width,512);assert.equal(meta.height,512);assert.equal(meta.format,'webp');assert.equal(meta.exif,undefined);assert.ok(result.length<=200*1024);
for(const f of [new File(['<svg/>'],'x.svg',{type:'image/svg+xml'}),new File(['junk'],'x.jpg',{type:'image/jpeg'}),new File([await (await image()).arrayBuffer()],'x.png',{type:'image/png'}),new File([Buffer.alloc(3*1024*1024+1)],'x.jpg',{type:'image/jpeg'}),new File([await sharp({create:{width:5000,height:5000,channels:3,background:'white'}}).png().toBuffer()],'big.png',{type:'image/png'})])await assert.rejects(()=>normalize(f));
const animated=await sharp(Buffer.from([255,0,0,255,0,0,255,255]),{raw:{width:1,height:2,channels:4,pageHeight:1}}).webp({loop:0,delay:[100,100]}).toBuffer();assert.equal((await sharp(animated).metadata()).pages,2);await assert.rejects(()=>normalize(new File([animated],'animated.webp',{type:'image/webp'})));
});
test('profile API denies unauthenticated/nonowners/background spoof and stale revision before storage writes',async()=>{for(const denied of [401,403]){const s={denied};assert.equal((await load('lib/tutor-profile-api.ts',s).saveTutorProfile(request(data()))).status,denied);assert.equal(s.upload,undefined);}
for(const [s,body,status] of [[{noTutor:true},data(),403],[{},data({background:'Spoof'}),403],[{profile:{revision:4}},data({avatar_action:'replace'}),409]]){assert.equal((await load('lib/tutor-profile-api.ts',s).saveTutorProfile(request(body,await image()))).status,status);assert.equal(s.upload,undefined);}
});
test('profile API saves text without Storage and passes admin-only background through versioned RPC',async()=>{const s={};const r=await load('lib/tutor-profile-api.ts',s).saveTutorProfile(request(data({background:'Ngoại lệ'})),tid);assert.equal(r.status,200);assert.equal(s.adminRequired,true);assert.equal(s.calls[0].args.p_data.background,'Ngoại lệ');assert.equal(s.upload,undefined);});
test('profile API keeps old image on upload failure or uncertain save; cleans retired images only after successful publication',async()=>{for(const mode of ['uploadError','saveError','success','removeError']){const s={previous:tid+'/old.webp',...(mode==='success'?{}:{[mode]:true})};const r=await load('lib/tutor-profile-api.ts',s).saveTutorProfile(request(data({avatar_action:'replace'}),await image()));assert.ok(s.upload);assert.equal((await sharp(s.upload.buffer).metadata()).width,512);if(mode==='uploadError'||mode==='saveError'){assert.ok(r.status>=400);assert.equal(s.removed,undefined);}else{assert.equal(r.status,200);assert.deepEqual(s.removed,[s.previous]);if(mode==='removeError')assert.equal(s.deleted,undefined);}}
});
test('cleanup respects SQL claim and never removes an attached image',async()=>{const s={claim:false};assert.equal(await load('lib/tutor-profile-api.ts',s).cleanupTutorAvatar(tid+'/used.webp'),false);assert.equal(s.removed,undefined);});
module.exports={load};
