import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowRight, ArrowUpRight } from 'lucide-react';
import curriculum from '@/lib/learning-curriculum-20260922.json';
import { PublicShell } from '@/components/marketing/PublicShell';
import { CodeIcon, GlyphHeading } from '@/components/marketing/PublicMotion';
import { PublicConsultation } from '@/components/marketing/PublicConsultation';
import '@/components/marketing/roadmap-experience.css';

const catalog = {
  a: { code: 'A', title: 'Nhập môn lập trình', heading: ['Hiểu từng lệnh.', 'Viết có ý tưởng.'], summary: 'Một chương trình bắt đầu từ việc hiểu dữ liệu và các bước xử lý. Lớp A giới thiệu C++ qua nhập, xuất dữ liệu, kiểu dữ liệu, điều kiện và vòng lặp. Mảng, hàm và xâu giúp bạn tiếp tục tổ chức dữ liệu, chia nhỏ công việc và diễn đạt cách giải rõ ràng hơn.', audience: 'Học sinh lớp 5–7 muốn bắt đầu với C++ và tìm hiểu cách giải bài toán bằng chương trình.', foundation: 'Bạn có thể bắt đầu từ môi trường lập trình và những thao tác nhập, xuất dữ liệu. Gia sư sẽ cùng bạn trao đổi điều đã học và mục tiêu trước khi chọn hướng học.', asset: 'basic-class', price: '99.000đ', part: 'A' },
  b: { code: 'B', title: 'Lập trình thi đấu cơ bản', heading: ['Nhận ra quy luật.', 'Tìm thêm cách giải.'], summary: 'Cùng một bài toán, có thể xét từng phương án hoặc khai thác tính chất của dữ liệu để tìm lời giải. Lớp B mở rộng từ vét cạn, thống kê và số học sang vector, pair, struct, map, sắp xếp, chặt nhị phân và xử lý xâu. Những kiến thức này tạo cơ sở để trao đổi cách lựa chọn phương pháp khi luyện bài.', audience: 'Học sinh lớp 7–9 quan tâm HSG cấp Phường hoặc Chuyên Tin. Phạm vi ôn luyện được trao đổi theo mục tiêu cụ thể.', foundation: 'Nhìn lại điều kiện, vòng lặp, mảng, hàm và xâu qua các bài bạn đã làm. Từ đó, cùng gia sư chọn phần cần củng cố hoặc nội dung muốn học tiếp.', asset: 'basic-class', price: '99.000đ', part: 'B' },
  c: { code: 'C', title: 'Lập trình thi đấu nâng cao', heading: ['Phân tích sâu.', 'Giải có cơ sở.'], summary: 'Khi cách duyệt đơn giản chưa phù hợp, cần nhìn lại cấu trúc dữ liệu và mối liên hệ giữa các bước giải. Lớp C kết nối cộng dồn, mảng hiệu, hai con trỏ với đệ quy, chia để trị, quay lui, tham lam, chặt nhị phân trên đáp án và băm xâu. Quy hoạch động tiếp tục mở ra cách mô tả trạng thái và giải những bài toán con có liên hệ. Nội dung gồm đầy đủ 19 chủ đề C+D.', audience: 'Học sinh lớp 7–9 quan tâm HSG tỉnh hoặc Chuyên Tin, muốn đào sâu cấu trúc dữ liệu và các phương pháp giải bài toán.', foundation: 'Chia sẻ cách bạn dùng C++, mảng, xâu và hàm, cùng những bài đã tự viết và kiểm tra lời giải. Việc học thực tế là cơ sở để trao đổi điểm bắt đầu.', asset: 'books', price: '109.000đ', part: 'CD' },
  e: { code: 'E', title: 'PreVOI', heading: ['PreVOI.', 'Hướng tới HSG Quốc gia.'], summary: 'PreVOI là hướng học dành cho mục tiêu HSG Quốc gia Tin học. Bắt đầu bằng việc nhìn lại những bài đã luyện, cách bạn phân tích đề và các vấn đề còn vướng; cùng đội ngũ CSAT trao đổi nội dung cần đào sâu và hướng ôn luyện cho mục tiêu này.', audience: 'Người học quan tâm HSG Quốc gia Tin học, muốn trao đổi hướng ôn luyện từ nền tảng và mục tiêu của mình.', foundation: 'Hãy chia sẻ kiến thức đã học, kinh nghiệm luyện bài và điều bạn muốn tìm hiểu thêm. Nội dung, nền tảng cần có và cách tổ chức học được trao đổi trực tiếp cùng đội ngũ.', asset: 'code-building', price: '', part: '' },
  k: { code: 'K', title: 'Kèm riêng', heading: ['Học điều cần học.', 'Theo nhịp của bạn.'], summary: 'Có lúc bạn muốn hệ thống lại kiến thức, có lúc cần thêm thời gian cho một dạng bài. Lớp K tổ chức học 1–1 hoặc nhóm đăng ký riêng, cùng gia sư chọn nội dung từ các chương trình đã được duyệt. Phạm vi và nhịp học được trao đổi theo mục tiêu, phần cần củng cố và thời gian bạn có thể dành cho việc học.', audience: 'Người học muốn học 1–1 hoặc cùng nhóm đăng ký riêng, với nội dung được trao đổi theo nhu cầu cụ thể.', foundation: 'Chia sẻ nội dung đã học, những phần còn vướng và thời gian có thể luyện tập. Cùng đội ngũ thống nhất phạm vi, hình thức, lịch và học phí trước khi bắt đầu.', asset: 'code4', price: '', part: '' },
  'co-ban': { code: 'A+B', title: 'Cơ bản · A+B', heading: ['Hiểu câu lệnh.', 'Tìm lời giải.'], summary: 'Phần A giới thiệu cách diễn đạt ý tưởng bằng C++; phần B kết nối những thao tác đã học với số học, tổ chức dữ liệu, sắp xếp và tìm kiếm. Toàn bộ A+B gồm 24 chủ đề, giúp bạn nhìn rõ mối liên hệ giữa việc viết chương trình và lựa chọn cách giải bài toán.', audience: 'Người học muốn bắt đầu với C++ hoặc hệ thống lại nền tảng. Phần A hướng đến học sinh lớp 5–7, phần B hướng đến lớp 7–9.', foundation: 'Khung Cơ bản mặc định gồm A+B. Cùng CSAT trao đổi nội dung đã học và các bài đã làm để chọn điểm bắt đầu, thay vì chỉ dựa vào cấp học.', asset: 'basic-class', price: '', part: 'AB' },
} as const;
type CourseKey = keyof typeof catalog;
const aliases: Record<string, CourseKey> = { 'nang-cao': 'c', advanced: 'c', hsgqg: 'e', voi: 'e', prevoi: 'e', custom: 'k', 'tuy-chinh': 'k', basic: 'co-ban' };
function resolve(program: string): CourseKey | undefined { return Object.hasOwn(catalog, program) ? program as CourseKey : Object.hasOwn(aliases, program) ? aliases[program] : undefined; }
export function generateStaticParams() { return [...Object.keys(catalog), ...Object.keys(aliases)].map(program => ({ program })); }
export const dynamicParams = false;
export async function generateMetadata({ params }: { params: Promise<{ program: string }> }): Promise<Metadata> {
  const { program } = await params;
  const key = resolve(program);
  if (!key) return { title: 'Không tìm thấy lộ trình — CSAT' };
  const course = catalog[key];
  return { title: `${course.code} — ${course.title} · CSAT`, description: course.summary, alternates: { canonical: `https://portal.csatoj.vn/lo-trinh/${key}` } };
}
const contextValues: Record<string, Record<string, string>> = {
  level: { primary: 'Tiểu học', thcs: 'THCS', thpt: 'THPT', university: 'Đại học' },
  goal: { undecided: 'Khám phá, cần trao đổi thêm', start: 'Bắt đầu học lập trình', thcs: 'HSG cấp THCS', specialist: 'Chuyên Tin', province: 'HSG tỉnh cấp THPT', national: 'HSG Quốc gia' },
  background: { unsure: 'Chưa rõ, muốn trao đổi', new: 'Chưa học lập trình', syntax: 'Đang làm quen cú pháp', practice: 'Đã tự giải một số bài lập trình' },
};
export default async function CoursePage({ params, searchParams }: { params: Promise<{ program: string }>; searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const [{ program }, search] = await Promise.all([params, searchParams]);
  const key = resolve(program);
  if (!key) notFound();
  const course = catalog[key];
  const template = curriculum.find(item => item.program === (key === 'c' ? 'advanced' : 'basic'))!;
  const stages = ['A', 'B', 'AB', 'CD'].includes(course.part) ? template.stages.filter(stage => course.part !== 'A' && course.part !== 'B' || stage.part === course.part) : [];
  const count = stages.reduce((total, stage) => total + stage.lessons.length, 0);
  const query = new URLSearchParams();
  const context = [`${course.code} — ${course.title}`];
  for (const [name, options] of Object.entries(contextValues)) {
    const value = search[name];
    if (typeof value === 'string' && Object.hasOwn(options, value)) { query.set(name, value); context.push(options[value]); }
  }
  const linkTo = (code: string) => `/lo-trinh/${code}${query.size ? `?${query}` : ''}`;
  return <PublicShell><div className="roadmap-experience rm-course-page">
    <header className="wrap rm-course-intro"><nav className="rm-breadcrumb" aria-label="Đường dẫn"><Link href="/">Giới thiệu</Link><span>/</span><Link href="/lo-trinh">Lộ trình học tập</Link><span>/</span><span>{course.code}</span></nav><div className="rm-course-hero"><div><p className="eyebrow">{key === 'co-ban' ? 'Khung kiến thức' : `Lớp ${course.code}`} / {course.title}</p><GlyphHeading as="h1">{course.heading[0]}<br /><em>{course.heading[1]}</em></GlyphHeading><p className="rm-course-lead">{course.summary}</p><a className="btn" href="#tu-van">Trao đổi về hướng học này <ArrowRight aria-hidden="true" size={18} /></a></div><div className="rm-course-photo"><Image src={`/images/site/${course.asset}.webp`} alt="" width={960} height={640} priority sizes="(max-width: 800px) 90vw, 40vw" /><span aria-hidden="true">{course.code}</span></div></div>
      <nav className="rm-course-switch" aria-label="Khám phá các lớp">{Object.entries(catalog).filter(([slug]) => slug !== 'co-ban').map(([slug, item]) => <Link href={linkTo(slug)} key={slug} aria-current={key === slug ? 'page' : undefined}><b>{item.code}</b>{item.title}<ArrowUpRight aria-hidden="true" size={16} /></Link>)}</nav>
      <div className="rm-course-facts"><div><span className="mono">HƯỚNG HỌC</span><p>{course.audience}</p></div><div><span className="mono">CÙNG CHỌN ĐIỂM BẮT ĐẦU</span><p>{course.foundation}</p></div><div><span className="mono">THÔNG TIN LỚP</span>{course.price ? <><strong>{course.price}<small> / buổi</small></strong><p>90 phút · 5–8 học sinh.<br />Lịch học theo đợt tuyển sinh; trao đổi cụ thể cùng đội ngũ trước khi đăng ký.</p></> : <p>{key === 'co-ban' ? 'Xem thông tin từng lớp A, B hoặc cùng đội ngũ trao đổi về lịch học và lựa chọn phạm vi.' : 'Trao đổi cụ thể cùng đội ngũ về nền tảng, lịch học, thời lượng và học phí.'}</p>}</div></div>
    </header>
    {stages.length > 0 ? <section className="rm-course-curriculum"><div className="wrap"><div className="rm-chapter mono"><span>NỘI DUNG HỌC TẬP / {course.code}</span><span>{count} CHỦ ĐỀ / {stages.length} CHẶNG</span></div><div className="rm-curriculum-heading"><GlyphHeading>Từng chủ đề.<br /><em>Thêm cách giải.</em></GlyphHeading><p>Các chặng dưới đây nhóm những kiến thức có liên hệ với nhau, từ khái niệm đến kỹ thuật vận dụng. Xem từng chủ đề để hình dung nội dung học; bài luyện tập và phần cần củng cố được trao đổi theo việc học thực tế.</p></div>{key === 'co-ban' && <nav className="rm-part-links" aria-label="Phạm vi kiến thức Cơ bản"><Link href={linkTo('a')}>A · 9 chủ đề</Link><Link href={linkTo('b')}>B · 15 chủ đề</Link><span aria-current="page">A+B · 24 chủ đề</span></nav>}<div className="rm-curriculum-stages">{stages.map((stage, index) => <details className="rm-curriculum-stage" key={stage.id} open={index === 0}><summary><span className="rm-stage-index mono">{String(index + 1).padStart(2, '0')} / {stage.part}</span><span><strong>{stage.title}</strong><small>{stage.lessons.length} chủ đề</small></span><span className="rm-stage-toggle" aria-hidden="true">+</span></summary><div className="rm-stage-body"><p>{stage.description.replace(/^Con /, 'Học sinh ')}</p><ol>{stage.lessons.map(lesson => <li key={lesson.code}><span className="mono">{lesson.code}</span><div><h3>{lesson.title}</h3>{lesson.description && <p>{lesson.description}</p>}</div></li>)}</ol></div></details>)}</div></div></section> : <section className="wrap rm-special-content"><div><p className="eyebrow">{course.code} / Cùng trao đổi hướng học</p><GlyphHeading>{key === 'e' ? <>Mục tiêu Quốc gia.<br /><em>Cùng chọn hướng học.</em></> : <>Tập trung điều cần học.<br /><em>Theo nhịp của bạn.</em></>}</GlyphHeading><p>{key === 'e' ? 'Bạn đang luyện những dạng bài nào, cách giải nào còn chưa rõ? Chia sẻ cùng CSAT để trao đổi hướng ôn luyện HSG Quốc gia, những nội dung cần đào sâu và cách tổ chức học phù hợp.' : 'Một chủ đề cần củng cố hay một nhóm kiến thức muốn tìm hiểu thêm đều có thể là điểm bắt đầu. Cùng gia sư chọn nội dung từ các khung đã duyệt, rồi thống nhất hình thức 1–1 hoặc nhóm riêng và thời gian học.'}</p></div><div className="rm-special-steps">{['Chia sẻ nền tảng và mục tiêu', 'Cùng trao đổi nội dung, hình thức học', 'Thống nhất lịch và học phí'].map((step, index) => <div key={step}><span className="mono">0{index + 1}</span><h3>{step}</h3><CodeIcon name={index === 0 ? 'brackets' : index === 1 ? 'branch' : 'loop'} /></div>)}</div></section>}
    <section className="rm-consult-section" id="tu-van"><div className="wrap rm-consult-layout"><div><p className="eyebrow">Cùng CSAT chọn bước tiếp theo</p><GlyphHeading>Chia sẻ việc học.<br /><em>Cùng chọn hướng đi.</em></GlyphHeading><p>Bạn đang quan tâm {course.title.toLowerCase()}? Hãy bắt đầu từ những điều đã học và mục tiêu muốn hướng tới.</p><div className="rm-consult-context"><span className="mono">NỘI DUNG QUAN TÂM</span><p>{context.join(' · ')}</p></div></div><PublicConsultation kind="consultation" context={context.join(' · ')} /></div></section>
  </div></PublicShell>;
}
